### PR TITLE
time zone generalisation 

### PR DESCRIPTION
**Pull request by soumyarai2050**

### CODE REVIEW

**Comment by soumyarai2050** [comment]
Running tests in Non India locations fails + mock file access assumes linux like env

Following 2 tests still failing:
1. test_order_timezone
2. test_candlestick_timezone

**Review by uberdeveloper — APPROVED** [review]

**Comment by uberdeveloper** [comment]
> Running tests in Non India locations fails + mock file access assumes linux like env
> 
> Following 2 tests still failing:
> 
> 1. test_order_timezone
> 2. test_candlestick_timezone

**Review by uberdeveloper — COMMENTED** [review]
Hi,
Did you run this on a windows environment?

**Comment by uberdeveloper** [comment]
@soumyarai2050 I have used the `PurePath` library and the new path syntax to improve upon your idea
Kindly update whether it runs on your machine.
The tests are also fixed

**Comment by soumyarai2050** [comment]
looks great - thanks

**Pull request closed without merging**
